from typing import Any, List, Optional, Union

import numpy as np
import sapien.core as sapien
import sapien.render
import torch

from mani_skill import PACKAGE_ASSET_DIR
from mani_skill.agents.robots import Fetch, Panda
from mani_skill.envs.sapien_env import BaseEnv
from mani_skill.envs.utils import randomization
from mani_skill.sensors.camera import CameraConfig
from mani_skill.utils import common, sapien_utils
from mani_skill.utils.registration import register_env
from mani_skill.utils.scene_builder.table import TableSceneBuilder
from mani_skill.utils.structs.pose import Pose

# Per-letter/digit OBJ meshes (generated by scripts/extract_letters.py and extract_numbers.py)
LETTER_MESH_DIR = PACKAGE_ASSET_DIR / "objects/letters"

# Distinct RGBA colors for up to 8 unique letters (wraps if word has repeated chars)
_PALETTE = [
    [0.85, 0.15, 0.15, 1.0],  # red
    [0.15, 0.50, 0.85, 1.0],  # blue
    [0.15, 0.75, 0.20, 1.0],  # green
    [0.90, 0.60, 0.10, 1.0],  # orange
    [0.60, 0.15, 0.80, 1.0],  # purple
    [0.10, 0.75, 0.75, 1.0],  # cyan
    [0.85, 0.85, 0.10, 1.0],  # yellow
    [0.85, 0.40, 0.60, 1.0],  # pink
]

# Letter mesh scale (applied to OBJ meshes); 2× original for visibility
LETTER_SCALE = [2.0, 2.0, 2.0]

# Fallback box half-size when no mesh exists for a letter (8cm × 6cm × 2.4cm — 2× original)
TILE_HALF_SIZE = [0.040, 0.030, 0.012]

# Target row: letters laid out left-to-right, centered at this table position
TARGET_CENTER = [-0.10, 0.00]
TILE_SPACING = 0.130   # center-to-center (m) — doubled with letter scale

# Spawn region for letters at episode start (random layout)
SPAWN_BOUNDS = [[-0.05, -0.20], [0.15, 0.20]]

# Fixed spawn position for letters when fixed_layout=True:
# tiles appear in a row at this x, same y-spacing as targets, 0° in-plane rotation.
FIXED_SPAWN_CENTER_X = 0.08

# Success / reward thresholds
PLACE_THRESH = 0.025   # letter xy distance to target for "placed"
MAX_LETTERS = 6        # cap word length so tiles fit on table


def _build_letter(scene, letter: str, name: str, color: List[float], kinematic: bool = False):
    """
    Build a letter actor. Uses the per-letter STL mesh if available,
    otherwise falls back to a plain box tile.
    """
    builder = scene.create_actor_builder()
    mat = sapien.render.RenderMaterial(base_color=color)
    # Emission so palette color is visible under overhead lighting
    mat.emission = [color[0], color[1], color[2], 1.0]
    key = letter.upper() if letter.isalpha() else letter
    mesh_path = LETTER_MESH_DIR / f"{key}.obj"

    if mesh_path.exists():
        if not kinematic:
            phys = sapien.pysapien.physx.PhysxMaterial(
                static_friction=1.5, dynamic_friction=1.5, restitution=0.0
            )
            builder.add_convex_collision_from_file(str(mesh_path), scale=LETTER_SCALE, material=phys)
        builder.add_visual_from_file(str(mesh_path), scale=LETTER_SCALE, material=mat)
    else:
        # Fallback: plain box
        half_size = TILE_HALF_SIZE
        if not kinematic:
            phys = sapien.pysapien.physx.PhysxMaterial(
                static_friction=1.5, dynamic_friction=1.5, restitution=0.0
            )
            builder.add_box_collision(half_size=half_size, material=phys)
        builder.add_box_visual(half_size=half_size, material=mat)

    builder.initial_pose = sapien.Pose(p=[0, 0, 0.5])
    if kinematic:
        return builder.build_kinematic(name=name)
    return builder.build(name=name)


@register_env("PushText-v1", max_episode_steps=200)
class PushTextEnv(BaseEnv):
    """
    **Task Description:**
    Pick up and place flat letter tiles on a table to spell a target word.
    The robot must move each tile to its target position in left-to-right order.
    It can push tiles or pick-and-place them — any strategy that works.

    **Randomizations:**
    - Each letter tile spawns at a random (x, y, z-rotation) on the table,
      with non-overlapping positions guaranteed by UniformPlacementSampler.

    **Success Conditions:**
    - Every letter tile is within PLACE_THRESH of its target xy position,
      is stationary, and is not being held by the gripper.

    **Bi-manual extension:**
    Pass robot_uids=("panda_wristcam", "panda_wristcam") to use two arms.
    """

    SUPPORTED_ROBOTS = ["panda_wristcam", "panda", "fetch"]
    agent: Union[Panda, Fetch]

    def __init__(
        self,
        *args,
        robot_uids="panda_wristcam",
        robot_init_qpos_noise: float = 0.02,
        goal_text: str = "AT",
        fixed_layout: bool = False,
        **kwargs,
    ):
        self.robot_init_qpos_noise = robot_init_qpos_noise
        self.goal_text = goal_text.upper().replace(" ", "")[:MAX_LETTERS]
        self.fixed_layout = fixed_layout
        super().__init__(*args, robot_uids=robot_uids, **kwargs)

    @property
    def _default_sensor_configs(self):
        # Straight down over letter area — robot arm stays out of frame.
        # up=(1,0,0) gives the correct table orientation for letter reading.
        pose = sapien_utils.look_at(eye=[-0.1, 0, 1.1], target=[-0.1, 0, 0], up=(1, 0, 0))
        return [CameraConfig("base_camera", pose, 256, 256, np.pi / 3, 0.01, 100)]

    @property
    def _default_human_render_camera_configs(self):
        # Angled overhead view showing the full scene
        pose = sapien_utils.look_at(eye=[0.3, 0.5, 0.8], target=[-0.1, 0, 0])
        return CameraConfig("render_camera", pose, 512, 512, 1.2, 0.01, 100)

    def _load_agent(self, options: dict):
        super()._load_agent(options, sapien.Pose(p=[-0.615, 0, 0]))

    # ------------------------------------------------------------------
    # Table-view camera (robot arm hidden)
    # ------------------------------------------------------------------

    def _collect_robot_render_bodies(self):
        """Collect all RenderBodyComponents from robot links (cached)."""
        if hasattr(self, "_robot_render_bodies"):
            return self._robot_render_bodies
        bodies = []
        for link in self.agent.robot.links:
            for phys_link in link._objs:
                for comp in phys_link.entity.components:
                    if isinstance(comp, sapien.render.RenderBodyComponent):
                        bodies.append(comp)
        self._robot_render_bodies = bodies
        return bodies

    def get_table_view(self) -> Optional[np.ndarray]:
        """
        Return a (H, W, 3) uint8 RGB image of the table from base_camera
        with the robot arm hidden. Returns None if rendering is unavailable.
        """
        if not self.scene.can_render():
            return None
        cam_sensor = self._sensors.get("base_camera")
        if cam_sensor is None:
            return None
        try:
            bodies = self._collect_robot_render_bodies()
            for body in bodies:
                body.visibility = 0
            self.scene.update_render(update_sensors=True, update_human_render_cameras=False)
            cam_sensor.capture()
            obs = cam_sensor.get_obs(rgb=True, depth=False, position=False, segmentation=False)
            rgb = obs["rgb"]  # (H, W, 3) or (B, H, W, 3) torch uint8
            if rgb.ndim == 4:
                rgb = rgb[0]
            img = rgb.cpu().numpy()
        except Exception:
            img = None
        finally:
            for body in bodies:
                body.visibility = 1
        return img

    # ------------------------------------------------------------------
    # Scene
    # ------------------------------------------------------------------

    def _load_scene(self, options: dict):
        self.tile_half_size = common.to_tensor(TILE_HALF_SIZE, device=self.device)
        self.table_scene = TableSceneBuilder(
            env=self, robot_init_qpos_noise=self.robot_init_qpos_noise
        )
        self.table_scene.build()

        n = len(self.goal_text)

        # Compute fixed target positions (row centered on table)
        total_span = (n - 1) * TILE_SPACING
        self.target_xys: List[List[float]] = []
        for i in range(n):
            tx = TARGET_CENTER[0]
            ty = TARGET_CENTER[1] - total_span / 2 + i * TILE_SPACING
            self.target_xys.append([tx, ty])

        # Build one moveable tile + one ghost target marker per letter
        self.letter_tiles = []
        self.target_markers = []
        # assign colors by letter character so same letter always same color
        self._char_color = {}
        color_idx = 0
        for ch in self.goal_text:
            if ch not in self._char_color:
                self._char_color[ch] = _PALETTE[color_idx % len(_PALETTE)]
                color_idx += 1

        for i, ch in enumerate(self.goal_text):
            color = self._char_color[ch]
            ghost = [color[0], color[1], color[2], 0.30]
            tile = _build_letter(self.scene, ch, f"tile_{i}_{ch}", color)
            marker = _build_letter(self.scene, ch, f"target_{i}_{ch}", ghost, kinematic=True)
            self.letter_tiles.append(tile)
            self.target_markers.append(marker)

    # ------------------------------------------------------------------
    # Episode init
    # ------------------------------------------------------------------

    def _initialize_episode(self, env_idx: torch.Tensor, options: dict):
        self._ocr_bonus = torch.zeros(self.num_envs, device=self.device)
        self._ocr_step_counter = 0
        with torch.device(self.device):
            b = len(env_idx)
            self.table_scene.initialize(env_idx)

            # 90° clockwise rotation around Z (looking down) so letters read correctly
            # quat = [cos(-45°), 0, 0, sin(-45°)] = [√2/2, 0, 0, -√2/2]
            _c = float(np.sqrt(2) / 2)
            target_q = torch.tensor([[_c, 0.0, 0.0, -_c]], device=self.device).expand(b, -1)

            # Place ghost markers at fixed target positions
            for marker, (tx, ty) in zip(self.target_markers, self.target_xys):
                xyz = torch.zeros(b, 3)
                xyz[:, 0] = tx
                xyz[:, 1] = ty
                xyz[:, 2] = TILE_HALF_SIZE[2] + 1e-3
                marker.set_pose(Pose.create_from_pq(p=xyz, q=target_q))

            if self.fixed_layout:
                # Fixed positions: one row at FIXED_SPAWN_CENTER_X, same y-spacing as
                # targets, identity in-plane rotation.  Every episode is identical.
                n = len(self.letter_tiles)
                total_span = (n - 1) * TILE_SPACING
                identity_q = torch.tensor([[1.0, 0.0, 0.0, 0.0]], device=self.device).expand(b, -1)
                for i, tile in enumerate(self.letter_tiles):
                    ty = TARGET_CENTER[1] - total_span / 2 + i * TILE_SPACING
                    xyz = torch.zeros(b, 3)
                    xyz[:, 0] = FIXED_SPAWN_CENTER_X
                    xyz[:, 1] = ty
                    xyz[:, 2] = TILE_HALF_SIZE[2] + 1e-3
                    tile.set_pose(Pose.create_from_pq(p=xyz, q=identity_q))
            else:
                # Random non-overlapping positions
                sampler = randomization.UniformPlacementSampler(
                    bounds=SPAWN_BOUNDS, batch_size=b, device=self.device
                )
                # minimum separation = diagonal of tile footprint + small gap
                radius = float(np.linalg.norm(TILE_HALF_SIZE[:2])) + 0.005

                center_xy = torch.zeros(b, 2)
                for tile in self.letter_tiles:
                    xy = center_xy + sampler.sample(radius, 100, verbose=False)
                    xyz = torch.zeros(b, 3)
                    xyz[:, :2] = xy
                    xyz[:, 2] = TILE_HALF_SIZE[2] + 1e-3
                    qs = randomization.random_quaternions(
                        b, lock_x=True, lock_y=True, lock_z=False, device=self.device
                    )
                    tile.set_pose(Pose.create_from_pq(p=xyz, q=qs))

    # ------------------------------------------------------------------
    # Evaluation
    # ------------------------------------------------------------------

    def _letter_dists(self) -> torch.Tensor:
        """Returns (b, n) xy distances from each tile to its target."""
        rows = []
        for tile, (tx, ty) in zip(self.letter_tiles, self.target_xys):
            target = torch.tensor([tx, ty], device=self.device)
            dist = torch.linalg.norm(tile.pose.p[:, :2] - target, dim=1)
            rows.append(dist)
        return torch.stack(rows, dim=1)  # (b, n)

    def evaluate(self):
        dists = self._letter_dists()                          # (b, n)
        is_placed = dists < PLACE_THRESH                      # (b, n)

        is_grasped = torch.stack(
            [self.agent.is_grasping(t) for t in self.letter_tiles], dim=1
        )  # (b, n)

        is_static = torch.stack(
            [t.is_static(lin_thresh=1e-2, ang_thresh=0.5) for t in self.letter_tiles],
            dim=1,
        )  # (b, n)

        success = (is_placed & is_static & ~is_grasped).all(dim=1)
        return {
            "letter_dists": dists,
            "is_placed": is_placed,
            "is_grasped": is_grasped,
            "is_static": is_static,
            "success": success,
        }

    # ------------------------------------------------------------------
    # Observations
    # ------------------------------------------------------------------

    def _get_obs_extra(self, info: dict):
        obs = dict(tcp_pose=self.agent.tcp.pose.raw_pose)
        if "state" in self.obs_mode:
            b = self.num_envs
            n = len(self.letter_tiles)
            tcp = self.agent.tcp.pose.p  # (b, 3)

            # Target quaternion: 90° CW around Z so letters read correctly in top-down view.
            # All tiles share the same target orientation.
            _c = float(np.sqrt(2) / 2)
            q_target = torch.tensor(
                [[_c, 0.0, 0.0, -_c]], device=self.device
            ).expand(b, -1)  # (b, 4)  [w, x, y, z]

            # q_target_inv = conjugate [w, -x, -y, -z] (valid for unit quaternions).
            q_target_inv = q_target * torch.tensor(
                [1.0, -1.0, -1.0, -1.0], device=self.device
            )

            def _quat_mul(q1, q2):
                w1, x1, y1, z1 = q1.unbind(-1)
                w2, x2, y2, z2 = q2.unbind(-1)
                return torch.stack([
                    w1*w2 - x1*x2 - y1*y2 - z1*z2,
                    w1*x2 + x1*w2 + y1*z2 - z1*y2,
                    w1*y2 - x1*z2 + y1*w2 + z1*x2,
                    w1*z2 + x1*y2 - y1*x2 + z1*w2,
                ], dim=-1)

            def _quat_to_axis_angle(q):
                """
                Convert unit quaternion [w,x,y,z] to axis-angle vector (3,).
                The axis defaults to world-Z (straight up from table) when the
                rotation angle is near zero, so the representation is continuous
                and centred on the correct axis for flat tiles.
                """
                w = q[..., 0:1].clamp(-1.0, 1.0)
                xyz = q[..., 1:]
                angle = 2.0 * torch.acos(w.abs())          # (b, 1), always ≥ 0
                sin_half = torch.sqrt(1.0 - w**2).clamp(min=1e-6)
                axis = xyz / sin_half                       # (b, 3), unit axis
                # When angle≈0 the axis is numerically unstable; default to +Z
                near_zero = (angle < 1e-6).expand_as(axis)
                z_up = torch.zeros_like(axis)
                z_up[..., 2] = 1.0
                axis = torch.where(near_zero, z_up, axis)
                # Flip so w≥0 (shortest-path convention keeps axis pointing up)
                axis = axis * torch.sign(w)
                return axis * angle                         # (b, 3)

            # (b, n*3): rotation error as axis-angle for each tile, flattened.
            # Zero vector means perfectly aligned with target; axis points along
            # world-Z at the start of each episode when tiles lie flat.
            letter_rot_to_target = torch.stack([
                _quat_to_axis_angle(_quat_mul(q_target_inv, t.pose.q))
                for t in self.letter_tiles
            ], dim=1).reshape(b, n * 3)

            # (b, n*3): 3-D vector from target position to tile position for each letter
            target_pos = torch.tensor(
                [[tx, ty, TILE_HALF_SIZE[2]] for tx, ty in self.target_xys],
                device=self.device,
            ).unsqueeze(0).expand(b, -1, -1)  # (b, n, 3)

            # (b, n*3): 3-D vector from TCP to each tile
            tcp_to_letters = torch.stack(
                [t.pose.p - tcp for t in self.letter_tiles], dim=1
            ).reshape(b, n * 3)

            # (b, n*3): 3-D vector from each tile to its target position
            letters_to_targets = (
                target_pos - torch.stack([t.pose.p for t in self.letter_tiles], dim=1)
            ).reshape(b, n * 3)

            obs.update(
                letter_rot_to_target=letter_rot_to_target,
                tcp_to_letters=tcp_to_letters,
                letters_to_targets=letters_to_targets,
            )
        return obs

    def get_language_instruction(self) -> List[str]:
        return [f"Arrange the letters to spell {self.goal_text}"] * self.num_envs

    # ------------------------------------------------------------------
    # OCR-based bonus (checked every OCR_CHECK_INTERVAL steps)
    # ------------------------------------------------------------------

    OCR_CHECK_INTERVAL = 20  # steps between OCR checks

    def _check_ocr_bonus(self) -> torch.Tensor:
        """
        Returns a (num_envs,) tensor with 1.0 if OCR detects all goal letters
        in the table view image. Only works for single-env CPU sim.
        """
        bonus = torch.zeros(self.num_envs, device=self.device)
        if self.num_envs != 1:
            return bonus
        img = self.get_table_view()
        if img is None:
            return bonus
        try:
            import cv2 as _cv2
            import easyocr
            if not hasattr(self, "_ocr_reader"):
                self._ocr_reader = easyocr.Reader(["en"], gpu=False, verbose=False)
            # Upscale 2x — OCR works better on larger images
            H, W = img.shape[:2]
            big = _cv2.resize(img, (W * 2, H * 2), interpolation=_cv2.INTER_LANCZOS4)
            results = self._ocr_reader.readtext(big, detail=0, paragraph=False)
            detected = "".join(results).upper().replace(" ", "")
            if self.goal_text in detected:
                bonus[0] = 1.0
        except Exception:
            pass
        return bonus

    # ------------------------------------------------------------------
    # Reward
    # ------------------------------------------------------------------

    def compute_dense_reward(self, obs: Any, action: torch.Tensor, info: dict):
        """
        Staged reward per letter (summed), mirroring StackCube's structure:
          Stage 0 — reach:  reward for TCP close to tile            [0, 2]
          Stage 1 — grasp:  reward for tile close to target         [4, 5]  (when grasped)
          Stage 2 — place:  reward for ungrasp + static after place [6, 7]  (when on target)
        Max raw reward = n_letters * 8; normalise to [0, 1] in the normalised fn.
        """
        n = len(self.letter_tiles)
        dists = info["letter_dists"]       # (b, n)
        is_grasped = info["is_grasped"]    # (b, n)
        is_placed = info["is_placed"]      # (b, n)
        is_static = info["is_static"]      # (b, n)

        tcp = self.agent.tcp.pose.p        # (b, 3)
        gripper_width = (self.agent.robot.get_qlimits()[0, -1, 1] * 2).to(self.device)

        reward = torch.zeros(self.num_envs, device=self.device)

        for i, tile in enumerate(self.letter_tiles):
            tile_pos = tile.pose.p                                    # (b, 3)
            tcp_to_tile_dist = torch.linalg.norm(tcp - tile_pos, dim=1)   # (b,)

            # Stage 0: reach
            letter_rew = 2 * (1 - torch.tanh(5 * tcp_to_tile_dist))  # (b,), max = 2.0 when TCP is on top of tile

            # Pre-grasp bridge: reward closing the gripper when TCP is near the tile.
            # Creates a gradient from "hover near tile" → "close gripper" → trigger is_grasping.
            # Active only when not yet grasped/placed; fades to zero beyond 10 cm.
            gripper_close_frac = 1.0 - (
                self.agent.robot.get_qpos()[:, -2:].sum(dim=1) / gripper_width
            )  # 0 = fully open, 1 = fully closed
            proximity = 1.0 - torch.clamp(tcp_to_tile_dist / 0.10, 0.0, 1.0)
            pre_grasp_rew = proximity * gripper_close_frac  # (b,), max = 1.0
            pre_grasp_rew = torch.where(
                is_grasped[:, i] | is_placed[:, i],
                torch.zeros_like(pre_grasp_rew),
                pre_grasp_rew,
            )
            letter_rew = letter_rew + pre_grasp_rew

            # Stage 1: grasped — reward for moving tile toward target
            ## Compute the vector from the tile to the target, and the tile's velocity vector. The reward is based on the cosine similarity between these vectors, encouraging the tile to move directly toward the target.
            direction_of_tile_to_target = torch.atan2(
                tile_pos[:, 1] - self.target_xys[i][1], tile_pos[:, 0] - self.target_xys[i][0]
            )  # (b,)
            tile_velocity_direction = torch.atan2(
                tile.linear_velocity[:, 1], tile.linear_velocity[:, 0]
            )  # (b,)
            angle_diff = torch.abs(direction_of_tile_to_target - tile_velocity_direction)
            angle_diff = torch.where(angle_diff > np.pi, 2 * np.pi - angle_diff, angle_diff)  # wrap to [0, π]
            direction_rew = 1.0 - angle_diff / np.pi  # (b,), 1.0 when perfectly aligned, 0.0 when moving perpendicular or away
            place_rew = 1 - torch.tanh(5.0 * dists[:, i])
            letter_rew = torch.where(is_grasped[:, i], 4 + place_rew, letter_rew)

            # Stage 2: placed — reward for releasing and becoming static
            ungrasp_rew = (
                self.agent.robot.get_qpos()[:, -2:].sum(dim=1) / gripper_width
            )
            ungrasp_rew = torch.where(~is_grasped[:, i], torch.ones_like(ungrasp_rew), ungrasp_rew)

            v = torch.linalg.norm(tile.linear_velocity, dim=1)
            av = torch.linalg.norm(tile.angular_velocity, dim=1)
            static_rew = 1 - torch.tanh(v * 10 + av)

            letter_rew = torch.where(
                is_placed[:, i], 6 + (ungrasp_rew + static_rew) / 2.0, letter_rew
            )

            # Full success for this letter
            letter_done = is_placed[:, i] & is_static[:, i] & ~is_grasped[:, i]
            letter_rew = torch.where(letter_done, torch.full_like(letter_rew, 8.0), letter_rew)

            reward += letter_rew

        reward[info["success"]] = float(n * 8)

        # OCR bonus: +2 when camera detects the goal word (checked every N steps)
        self._ocr_step_counter += 1
        if self._ocr_step_counter % self.OCR_CHECK_INTERVAL == 0:
            self._ocr_bonus = self._check_ocr_bonus() * 2.0
        reward = reward + self._ocr_bonus

        return reward

    def compute_normalized_dense_reward(self, obs: Any, action: torch.Tensor, info: dict):
        max_reward = len(self.letter_tiles) * 8.0 + 2.0  # +2 for OCR bonus
        return self.compute_dense_reward(obs=obs, action=action, info=info) / max_reward
