from typing import Any, List, Union

import numpy as np
import sapien.core as sapien
import torch

from mani_skill import PACKAGE_ASSET_DIR
from mani_skill.agents.robots import Fetch, Panda
from mani_skill.envs.sapien_env import BaseEnv
from mani_skill.envs.utils import randomization
from mani_skill.sensors.camera import CameraConfig
from mani_skill.utils import common, sapien_utils
from mani_skill.utils.registration import register_env
from mani_skill.utils.scene_builder.table import TableSceneBuilder
from mani_skill.utils.structs.pose import Pose

# Per-letter/digit OBJ meshes (generated by scripts/extract_letters.py and extract_numbers.py)
LETTER_MESH_DIR = PACKAGE_ASSET_DIR / "objects/letters"

# Distinct RGBA colors for up to 8 unique letters (wraps if word has repeated chars)
_PALETTE = [
    [0.85, 0.15, 0.15, 1.0],  # red
    [0.15, 0.50, 0.85, 1.0],  # blue
    [0.15, 0.75, 0.20, 1.0],  # green
    [0.90, 0.60, 0.10, 1.0],  # orange
    [0.60, 0.15, 0.80, 1.0],  # purple
    [0.10, 0.75, 0.75, 1.0],  # cyan
    [0.85, 0.85, 0.10, 1.0],  # yellow
    [0.85, 0.40, 0.60, 1.0],  # pink
]

# Fallback box half-size when no mesh exists for a letter (4cm × 3cm × 1.2cm)
TILE_HALF_SIZE = [0.020, 0.015, 0.006]

# Target row: letters laid out left-to-right, centered at this table position
TARGET_CENTER = [-0.10, 0.00]
TILE_SPACING = 0.065   # center-to-center (m)

# Spawn region for letters at episode start
SPAWN_BOUNDS = [[-0.05, -0.20], [0.15, 0.20]]

# Success / reward thresholds
PLACE_THRESH = 0.025   # letter xy distance to target for "placed"
MAX_LETTERS = 6        # cap word length so tiles fit on table


def _build_letter(scene, letter: str, name: str, color: List[float], kinematic: bool = False):
    """
    Build a letter actor. Uses the per-letter STL mesh if available,
    otherwise falls back to a plain box tile.
    """
    builder = scene.create_actor_builder()
    mat = sapien.render.RenderMaterial(base_color=color)
    key = letter.upper() if letter.isalpha() else letter
    mesh_path = LETTER_MESH_DIR / f"{key}.obj"

    if mesh_path.exists():
        if not kinematic:
            phys = sapien.pysapien.physx.PhysxMaterial(
                static_friction=1.5, dynamic_friction=1.5, restitution=0.0
            )
            builder.add_convex_collision_from_file(str(mesh_path), material=phys)
        builder.add_visual_from_file(str(mesh_path), material=mat)
    else:
        # Fallback: plain box
        half_size = TILE_HALF_SIZE
        if not kinematic:
            phys = sapien.pysapien.physx.PhysxMaterial(
                static_friction=1.5, dynamic_friction=1.5, restitution=0.0
            )
            builder.add_box_collision(half_size=half_size, material=phys)
        builder.add_box_visual(half_size=half_size, material=mat)

    builder.initial_pose = sapien.Pose(p=[0, 0, 0.5])
    if kinematic:
        return builder.build_kinematic(name=name)
    return builder.build(name=name)


@register_env("PushText-v1", max_episode_steps=200)
class PushTextEnv(BaseEnv):
    """
    **Task Description:**
    Pick up and place flat letter tiles on a table to spell a target word.
    The robot must move each tile to its target position in left-to-right order.
    It can push tiles or pick-and-place them — any strategy that works.

    **Randomizations:**
    - Each letter tile spawns at a random (x, y, z-rotation) on the table,
      with non-overlapping positions guaranteed by UniformPlacementSampler.

    **Success Conditions:**
    - Every letter tile is within PLACE_THRESH of its target xy position,
      is stationary, and is not being held by the gripper.

    **Bi-manual extension:**
    Pass robot_uids=("panda_wristcam", "panda_wristcam") to use two arms.
    """

    SUPPORTED_ROBOTS = ["panda_wristcam", "panda", "fetch"]
    agent: Union[Panda, Fetch]

    def __init__(
        self,
        *args,
        robot_uids="panda_wristcam",
        robot_init_qpos_noise: float = 0.02,
        goal_text: str = "AT",
        **kwargs,
    ):
        self.robot_init_qpos_noise = robot_init_qpos_noise
        self.goal_text = goal_text.upper().replace(" ", "")[:MAX_LETTERS]
        super().__init__(*args, robot_uids=robot_uids, **kwargs)

    @property
    def _default_sensor_configs(self):
        # Near-overhead view centered on the table, letter area fills frame
        pose = sapien_utils.look_at(eye=[0.0, 0, 0.5], target=[-0.1, 0, 0])
        return [CameraConfig("base_camera", pose, 128, 128, np.pi / 2, 0.01, 100)]

    @property
    def _default_human_render_camera_configs(self):
        # Overhead view so letters are clearly readable
        pose = sapien_utils.look_at(eye=[0.0, 0, 0.6], target=[-0.1, 0, 0])
        return CameraConfig("render_camera", pose, 512, 512, 1.2, 0.01, 100)

    def _load_agent(self, options: dict):
        super()._load_agent(options, sapien.Pose(p=[-0.615, 0, 0]))

    # ------------------------------------------------------------------
    # Scene
    # ------------------------------------------------------------------

    def _load_scene(self, options: dict):
        self.tile_half_size = common.to_tensor(TILE_HALF_SIZE, device=self.device)
        self.table_scene = TableSceneBuilder(
            env=self, robot_init_qpos_noise=self.robot_init_qpos_noise
        )
        self.table_scene.build()

        n = len(self.goal_text)

        # Compute fixed target positions (row centered on table)
        total_span = (n - 1) * TILE_SPACING
        self.target_xys: List[List[float]] = []
        for i in range(n):
            tx = TARGET_CENTER[0]
            ty = TARGET_CENTER[1] - total_span / 2 + i * TILE_SPACING
            self.target_xys.append([tx, ty])

        # Build one moveable tile + one ghost target marker per letter
        self.letter_tiles = []
        self.target_markers = []
        # assign colors by letter character so same letter always same color
        char_color = {}
        color_idx = 0
        for ch in self.goal_text:
            if ch not in char_color:
                char_color[ch] = _PALETTE[color_idx % len(_PALETTE)]
                color_idx += 1

        for i, ch in enumerate(self.goal_text):
            color = char_color[ch]
            ghost = [color[0], color[1], color[2], 0.30]
            self.letter_tiles.append(_build_letter(self.scene, ch, f"tile_{i}_{ch}", color))
            self.target_markers.append(
                _build_letter(self.scene, ch, f"target_{i}_{ch}", ghost, kinematic=True)
            )

    # ------------------------------------------------------------------
    # Episode init
    # ------------------------------------------------------------------

    def _initialize_episode(self, env_idx: torch.Tensor, options: dict):
        with torch.device(self.device):
            b = len(env_idx)
            self.table_scene.initialize(env_idx)

            # Place ghost markers at fixed target positions
            for marker, (tx, ty) in zip(self.target_markers, self.target_xys):
                xyz = torch.zeros(b, 3)
                xyz[:, 0] = tx
                xyz[:, 1] = ty
                xyz[:, 2] = TILE_HALF_SIZE[2] + 1e-3
                marker.set_pose(Pose.create_from_pq(p=xyz))

            # Spawn letter tiles at random non-overlapping positions
            sampler = randomization.UniformPlacementSampler(
                bounds=SPAWN_BOUNDS, batch_size=b, device=self.device
            )
            # minimum separation = diagonal of tile footprint + small gap
            radius = float(np.linalg.norm(TILE_HALF_SIZE[:2])) + 0.005

            center_xy = torch.zeros(b, 2)
            for tile in self.letter_tiles:
                xy = center_xy + sampler.sample(radius, 100, verbose=False)
                xyz = torch.zeros(b, 3)
                xyz[:, :2] = xy
                xyz[:, 2] = TILE_HALF_SIZE[2] + 1e-3
                qs = randomization.random_quaternions(
                    b, lock_x=True, lock_y=True, lock_z=False, device=self.device
                )
                tile.set_pose(Pose.create_from_pq(p=xyz, q=qs))

    # ------------------------------------------------------------------
    # Evaluation
    # ------------------------------------------------------------------

    def _letter_dists(self) -> torch.Tensor:
        """Returns (b, n) xy distances from each tile to its target."""
        rows = []
        for tile, (tx, ty) in zip(self.letter_tiles, self.target_xys):
            target = torch.tensor([tx, ty], device=self.device)
            dist = torch.linalg.norm(tile.pose.p[:, :2] - target, dim=1)
            rows.append(dist)
        return torch.stack(rows, dim=1)  # (b, n)

    def evaluate(self):
        dists = self._letter_dists()                          # (b, n)
        is_placed = dists < PLACE_THRESH                      # (b, n)

        is_grasped = torch.stack(
            [self.agent.is_grasping(t) for t in self.letter_tiles], dim=1
        )  # (b, n)

        is_static = torch.stack(
            [t.is_static(lin_thresh=1e-2, ang_thresh=0.5) for t in self.letter_tiles],
            dim=1,
        )  # (b, n)

        success = (is_placed & is_static & ~is_grasped).all(dim=1)
        return {
            "letter_dists": dists,
            "is_placed": is_placed,
            "is_grasped": is_grasped,
            "is_static": is_static,
            "success": success,
        }

    # ------------------------------------------------------------------
    # Observations
    # ------------------------------------------------------------------

    def _get_obs_extra(self, info: dict):
        obs = dict(tcp_pose=self.agent.tcp.pose.raw_pose)
        if "state" in self.obs_mode:
            b = self.num_envs
            n = len(self.letter_tiles)
            tcp = self.agent.tcp.pose.p  # (b, 3)

            # Flatten letter dim so all tensors are (b, n*k) — compatible with flatten_state_dict
            letter_poses = torch.stack(
                [t.pose.raw_pose for t in self.letter_tiles], dim=1
            ).reshape(b, n * 7)  # (b, n*7)

            target_pos = torch.tensor(
                [[tx, ty, TILE_HALF_SIZE[2]] for tx, ty in self.target_xys],
                device=self.device,
            ).unsqueeze(0).expand(b, -1, -1)  # (b, n, 3)

            tcp_to_letters = torch.stack(
                [t.pose.p - tcp for t in self.letter_tiles], dim=1
            ).reshape(b, n * 3)  # (b, n*3)

            letters_to_targets = (
                target_pos - torch.stack([t.pose.p for t in self.letter_tiles], dim=1)
            ).reshape(b, n * 3)  # (b, n*3)

            obs.update(
                letter_poses=letter_poses,
                target_positions=target_pos.reshape(b, n * 3),
                tcp_to_letters=tcp_to_letters,
                letters_to_targets=letters_to_targets,
            )
        return obs

    def get_language_instruction(self) -> List[str]:
        return [f"Arrange the letters to spell {self.goal_text}"] * self.num_envs

    # ------------------------------------------------------------------
    # Reward
    # ------------------------------------------------------------------

    def compute_dense_reward(self, obs: Any, action: torch.Tensor, info: dict):
        """
        Staged reward per letter (summed), mirroring StackCube's structure:
          Stage 0 — reach:  reward for TCP close to tile            [0, 2]
          Stage 1 — grasp:  reward for tile close to target         [4, 5]  (when grasped)
          Stage 2 — place:  reward for ungrasp + static after place [6, 7]  (when on target)
        Max raw reward = n_letters * 8; normalise to [0, 1] in the normalised fn.
        """
        n = len(self.letter_tiles)
        dists = info["letter_dists"]       # (b, n)
        is_grasped = info["is_grasped"]    # (b, n)
        is_placed = info["is_placed"]      # (b, n)
        is_static = info["is_static"]      # (b, n)

        tcp = self.agent.tcp.pose.p        # (b, 3)
        gripper_width = (self.agent.robot.get_qlimits()[0, -1, 1] * 2).to(self.device)

        reward = torch.zeros(self.num_envs, device=self.device)

        for i, tile in enumerate(self.letter_tiles):
            tile_pos = tile.pose.p                                    # (b, 3)
            tcp_to_tile = torch.linalg.norm(tcp - tile_pos, dim=1)   # (b,)

            # Stage 0: reach
            letter_rew = 2 * (1 - torch.tanh(5 * tcp_to_tile))

            # Stage 1: grasped — reward for moving tile toward target
            place_rew = 1 - torch.tanh(5.0 * dists[:, i])
            letter_rew = torch.where(is_grasped[:, i], 4 + place_rew, letter_rew)

            # Stage 2: placed — reward for releasing and becoming static
            ungrasp_rew = (
                self.agent.robot.get_qpos()[:, -2:].sum(dim=1) / gripper_width
            )
            ungrasp_rew = torch.where(~is_grasped[:, i], torch.ones_like(ungrasp_rew), ungrasp_rew)

            v = torch.linalg.norm(tile.linear_velocity, dim=1)
            av = torch.linalg.norm(tile.angular_velocity, dim=1)
            static_rew = 1 - torch.tanh(v * 10 + av)

            letter_rew = torch.where(
                is_placed[:, i], 6 + (ungrasp_rew + static_rew) / 2.0, letter_rew
            )

            # Full success for this letter
            letter_done = is_placed[:, i] & is_static[:, i] & ~is_grasped[:, i]
            letter_rew = torch.where(letter_done, torch.full_like(letter_rew, 8.0), letter_rew)

            reward += letter_rew

        reward[info["success"]] = float(n * 8)
        return reward

    def compute_normalized_dense_reward(self, obs: Any, action: torch.Tensor, info: dict):
        return self.compute_dense_reward(obs=obs, action=action, info=info) / (
            len(self.letter_tiles) * 8.0
        )
